const courseList = {
    course1: {
        image: "/courseImg/html.jpg",
        name: "Build a Responsive Website with HTML5, CSS3",
        price: "$30",
        intro: "Learn modern web design and code responsive websites from scratch using HTML5 and CSS3. Develop and code a huge project.",
        aboutthiscourse: "In this course, you’ll learn important vocabulary and strategies for writing effective emails, starting with the subject line.  You'll learn how to write messages for different audiences and understand when to be formal or direct. You’ll also learn how your choice of words can change the way people view your message. You'll practice writing emails to follow up with people in your network.",
        youwilllearn1: "You will learn how to create beautiful animations on scroll using basic JavaScript that will make your website look very professional.",
        youwilllearn2: "Learn the basic steps on how to make a website responsive to fit smaller screens and mobile devices.",
        youwilllearn3: "Feel comfortable with the process of coding, creating and designing any templates/websites from scratch",
        youwilllearn4: "Work with HTML5 section elements and CSS3 to structure a web site.",
        tutor: "Daphne Mackey",
        length: "3 weeks",
        effort: "3 to 5 hours per week",
        subject: "Html, CSS",
        language: "English"
    },
    course2: {
        image: "/courseImg/htmlcss.jpg",
        name: "HTML5 and CSS3 - Essential Training",
        price: "$30",
        intro: "Learn HTML5 / CSS3 and how to incorporate markup to build standards-compliant and forward-thinking responsive web sites.",
        aboutthiscourse: "In this course, you’ll learn important vocabulary and strategies for writing effective emails, starting with the subject line.  You'll learn how to write messages for different audiences and understand when to be formal or direct. You’ll also learn how your choice of words can change the way people view your message. You'll practice writing emails to follow up with people in your network.",
        youwilllearn1: "Know what powers the Web including HTML, CSS, and JavaScript.",
        youwilllearn2: "Understand every HTML5 tag and their associated attributes.",
        youwilllearn3: "Work with advanced structuring techniques using HTML5 and CSS3.",
        youwilllearn4: "Work with HTML5 section elements and CSS3 to structure a web site.",
        tutor: "Daphne Mackey",
        length: "3 weeks",
        effort: "3 to 5 hours per week",
        subject: "Html, CSS",
        language: "English"
    },
    course3: {
        image: "/courseImg/JavaScriptBasics.jpg",
        name: "JavaScript Basics for Beginners",
        price: "$30",
        intro: "JavaScript - Master the Fundamentals in 6 Hours",
        aboutthiscourse: "In this course, you’ll learn important vocabulary and strategies for writing effective emails, starting with the subject line.  You'll learn how to write messages for different audiences and understand when to be formal or direct. You’ll also learn how your choice of words can change the way people view your message. You'll practice writing emails to follow up with people in your network.",
        youwilllearn1: "Understand the fundamental concepts in JavaScript",
        youwilllearn2: "Learn and apply the best practices",
        youwilllearn3: "Write solid JavaScript code",
        youwilllearn4: "Avoid common pitfalls and mistakes other JavaScript developers make",
        tutor: "Daphne Mackey",
        length: "3 weeks",
        effort: "3 to 5 hours per week",
        subject: "Html, CSS",
        language: "English"
    },
    course4: {
        image: "/courseImg/asynchjs.jpg",
        name: "Asynchronous JavaScript",
        price: "$30",
        intro: "Become an expert in Asynchronous JavaScript, Callbacks, Promises, Async/Await, Generators & The Event Loop",
        aboutthiscourse: "In this course, you’ll learn important vocabulary and strategies for writing effective emails, starting with the subject line.  You'll learn how to write messages for different audiences and understand when to be formal or direct. You’ll also learn how your choice of words can change the way people view your message. You'll practice writing emails to follow up with people in your network.",
        youwilllearn1: "Ace any asynchronous JavaScript interview question",
        youwilllearn2: "Write fast performant JavaScript applications",
        youwilllearn3: "Spend less time chasing down bugs in asynchronous code",
        youwilllearn4: "Understand complex JavaScript concepts",
        tutor: "Daphne Mackey",
        length: "3 weeks",
        effort: "3 to 5 hours per week",
        subject: "Html, CSS",
        language: "English"
    },
    course5: {
        image: "/courseImg/react.jpg",
        name: "The complete React Fullstack course",
        price: "$30",
        intro: "Take you coding to the next level with React, Node js, MongoDB, Firebase, Webpack and ES6",
        aboutthiscourse: "In this course, you’ll learn important vocabulary and strategies for writing effective emails, starting with the subject line.  You'll learn how to write messages for different audiences and understand when to be formal or direct. You’ll also learn how your choice of words can change the way people view your message. You'll practice writing emails to follow up with people in your network.",
        youwilllearn1: "You will learn the whole React WebApp building process, from your pc to the server.",
        youwilllearn2: "How to deploy applications to services like Firebase and Heroku.",
        youwilllearn3: "Learn how Redux work and apply it on a real life application",
        youwilllearn4: "Learn the basics of Webpack",
        tutor: "Richard Moore",
        length: "3 weeks",
        effort: "3 to 5 hours per week",
        subject: "Html, CSS",
        language: "English"
    },
    course6: {
        image: "/courseImg/reactredux.jpg",
        name: "Learn React & Redux: From Beginner To Paid Professional",
        price: "$30",
        intro: "Become a damn good React and Redux developer in under 30 days",
        aboutthiscourse: "In this course, you’ll learn important vocabulary and strategies for writing effective emails, starting with the subject line.  You'll learn how to write messages for different audiences and understand when to be formal or direct. You’ll also learn how your choice of words can change the way people view your message. You'll practice writing emails to follow up with people in your network.",
        youwilllearn1: "You'll be able to build your own creative, fully functional web applications using React & Redux",
        youwilllearn2: "Complete confidence when interviewing for React & Redux dev roles with tips from a pro",
        youwilllearn3: "Create your own components with ease, then craft entire component hierarchies",
        youwilllearn4: "Learn practical React & Redux, allowing you to easily solve real world web development problems",
        tutor: "Richard Moore",
        length: "3 weeks",
        effort: "3 to 5 hours per week",
        subject: "Html, CSS",
        language: "English"
    }
}

export default courseList;